name: Test on Windows and macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        ruby-version: ['2.7', '3.2']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '${{matrix.ruby-version}}'  # Specify your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install

    - name: Run tests
      run: bundle exec rake
